services:
  api:
    image: node:22-alpine3.19
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
    networks:
      - network_TAMR
    command: "node /app/index.js"
  web:
    image: pokemon_app:1.0.0
    
    ports:
      - 80:80
    volumes:
      - ./app:/app
    networks:
      - network_TAMR 
  db:
    image: mysql:8.0.39
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
      - MYSQL_DATABASE='pokemon'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network_TAMR
  proxy:
    image: nginx:1.27.2-alpine
    networks:
      - network_TAMR

volumes:
  db_data:
networks:
  network_TAMR: